events { worker_connections 1024; }

http {
    # Define internal upstream service aliases matching docker container names
    upstream order_backend {
        server order-service:3000;
    }

    server {
        listen 80;

        # Health check endpoint for the Gateway itself
        location /health {
            return 200 '{"status": "Gateway Live"}';
            add_header Content-Type application/json;
        }

        # Routes client traffic from /api/orders down to the private Order Service
        location /api/orders {
            rewrite /api/(.*) /$1 break; # Strips '/api' from URL before forwarding
            proxy_pass http://order_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
